name: Build and deploy container

on:
  workflow_dispatch:
  
  push:
    branches:
    - main
    - release/*

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: 21
            distribution: temurin
            cache: maven
        - name: Build and package with Maven
          run: ./mvnw package

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/c3pochat:${{ github.sha }} .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/c3pochat:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/c3pochat:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secure-environment-variables: QUARKUS_LANGCHAIN4J_AZURE-OPENAI_API_KEY=${{ secrets.OPENAI_KEY }} QUARKUS_MONGODB_CONNECTION_STRING=${{ secrets.c3p0_mongodb_connection_string }}
            name: aci-c3pochat
            location: 'west us'
